
broker:
  enabled: false
  image: roadiehq/broker:4231273077.6.1-kubernetes
  serviceAccount:
    name: roadie-broker
    namespace: default
  deployment:
    name: roadie-broker
    namespace: default
  token:
  tenantName:

clusterRoleBinding:
  name: roadie-role-binding

clusterRole:
  name: roadie-read-access
  rules:
    set1:
      - apiGroups:
          - ""
        resources:
          - "pods"
          - "configmaps"
          - "services"
          - "deployments"
          - "replicasets"
          - "horizontalpodautoscalers"
          - "ingresses"
        verbs:
          - "get"
          - "list"
          - "watch"
    set2:
      - apiGroups:
          - "batch"
        resources:
          - "jobs"
          - "cronjobs"
        verbs:
          - "get"
          - "list"
          - "watch"
    set3:
      - apiGroups:
          - "extensions"
          - "apps"
          - "autoscaling"
          - "networking.k8s.io"
        resources:
          - "deployments"
          - "ingresses"
          - "replicasets"
          - "horizontalpodautoscalers"
        verbs:
          - "get"
          - "list"
          - "watch"

user:
  name: roadie
  namespace: default

