
broker:
  enabled: false
  image: "roadiehq/broker:kubernetes"
  imagePullSecret:
  serviceAccount:
    name: roadie-broker
    namespace: default
  deployment:
    name: roadie-broker
    namespace: default
  token: roadie-kube-api
  tenantName:
  securityContext:

serviceAccount:
  enabled: false
  name:
  namespace:

clusterRoleBinding:
  name:

clusterRole:
  name:
  rules:
    set1:
      - apiGroups:
          - ""
        resources:
          - "pods"
          - "configmaps"
          - "services"
          - "deployments"
          - "replicasets"
          - "horizontalpodautoscalers"
          - "ingresses"
          - "namespaces"
        verbs:
          - "get"
          - "list"
          - "watch"
    set2:
      - apiGroups:
          - "batch"
        resources:
          - "jobs"
          - "cronjobs"
        verbs:
          - "get"
          - "list"
          - "watch"
    set3:
      - apiGroups:
          - "extensions"
          - "apps"
          - "autoscaling"
          - "networking.k8s.io"
        resources:
          - "deployments"
          - "ingresses"
          - "replicasets"
          - "horizontalpodautoscalers"
        verbs:
          - "get"
          - "list"
          - "watch"

user:
  name: roadie
  namespace: default

