
broker:
  enabled: false
  image: "roadiehq/broker:13371353312.75.1-kubernetes"
  imagePullSecret:
  logLevel: debug
  logBody: false
  serverUrl: ""
  serviceAccount:
    name: roadie-k8s-broker
    namespace: default
  deployment:
    name: roadie-k8s-broker
    namespace: default
  token:
  tenantName:
  dnsConfig:
  securityContext:
  envFrom: []
  env: []
  nodeSelector: {}
  affinity: {}

serviceAccount:
  enabled: false
  name:
  namespace:

clusterRoleBinding:
  name:

clusterRole:
  name:
  rules:
    set1:
      - apiGroups:
          - ""
        resources:
          - "pods/log"
          - "pods"
          - "configmaps"
          - "services"
          - "deployments"
          - "replicasets"
          - "horizontalpodautoscalers"
          - "ingresses"
          - "namespaces"
          - "limitranges"
        verbs:
          - "get"
          - "list"
          - "watch"
    set2:
      - apiGroups:
          - "batch"
        resources:
          - "jobs"
          - "cronjobs"
        verbs:
          - "get"
          - "list"
          - "watch"
    set3:
      - apiGroups:
          - "extensions"
          - "apps"
          - "autoscaling"
          - "networking.k8s.io"
        resources:
          - "deployments"
          - "ingresses"
          - "replicasets"
          - "horizontalpodautoscalers"
          - "statefulsets"
          - "daemonsets"
        verbs:
          - "get"
          - "list"
          - "watch"
    set4:
      - apiGroups:
          - "metrics.k8s.io"
        resources:
          - "pods"
          - "namespaces"
        verbs:
          - "get"
          - "list"

user:
  name: roadie
  namespace: default

