# Default values for backstage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

techdocs:
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  requestUrl: http://localhost:7000/api/techdocs
backend:
  enabled: true
  replicaCount: 1
  image: roadiehq/backstage-k8s-demo-backend
  imagePullPolicy: IfNotPresent
  containerPort: 7000
  cors:
    origin: https://demo.example.com
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

lighthouse:
  enabled: false
  replicaCount: 1
  image:
    repository: roadiehq/lighthouse-audit-service
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 3003
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

gitops:
  enabled: false
  replicaCount: 1
  image:
    repository: chanwit/gitops-api
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

nameOverride: ""
fullnameOverride: ""

ingress:
  host: demo.example.com
  tls: []

auth:

issuer:
  email: hello@example.com
jenkins:
  url: http://jenkins.jenkins:8080
  authHeader: "Basic dummy-token"