# Default values for backstage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: roadiehq/backstage-k8s-demo-frontend
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

backend:
  enabled: true
  replicaCount: 1
  image:
    repository: roadiehq/backstage-k8s-demo-backend
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 7000
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

lighthouse:
  enabled: false
  replicaCount: 1
  image:
    repository: roadiehq/lighthouse-audit-service
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 3003
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

gitops:
  enabled: false
  replicaCount: 1
  image:
    repository: chanwit/gitops-api
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

nameOverride: ""
fullnameOverride: ""

ingress:
  hosts:
    - host: demo.example.com
      paths:
        - service: frontend
    - host: backend.example.com
      paths:
        - service: backend
  tls: []

appConfig:
  app:
    baseUrl: backstage.example.com
    title: Backstage
  backend:
    baseUrl: https://backend.example.com
    cors:
      origin: https://backend.example.com
  auth:
    github:
      development:
        appOrigin: "http://localhost:3000/"

auth:
  google:
    clientId: a
    clientSecret: a
  github:
    clientId: c
    clientSecret: c
  gitlab:
    clientId: b
    clientSecret: b
    baseUrl: b
  okta:
    clientId: b
    clientSecret: b
    audience: b
  oauth2:
    clientId: b
    clientSecret: b
    authUrl: b
    tokenUrl: b
  sentryToken: e
  rollbarAccountToken: f

issuer:
  email: hello@example.com
