frontend:
  replicaCount: 1
  image:
    repository: hmctspublic.azurecr.io/backstage/frontend
    tag: v7
ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  enabled: true
  hosts:
    - host: backstage.sandbox.platform.hmcts.net
      paths:
        - service: frontend
    - host: backstage-api.sandbox.platform.hmcts.net
      paths:
        - service: backend
backend:
  replicaCount: 1
  image:
    repository: hmctspublic.azurecr.io/backstage/backend
    tag: v4


appConfig:
  app:
    baseUrl: backstage.sandbox.platform.hmcts.net
    title: HMCTS Backstage
  backend:
    baseUrl: https://backstage-api.sandbox.platform.hmcts.net
    db:
      user: backstage@hmcts-backstage-sbox
      host: hmcts-backstage-sbox.postgres.database.azure.com
      password: 'add-here'
    cors:
      origin: https://backstage.sandbox.platform.hmcts.net
  auth:
    github:
      development:
        appOrigin: "https://backstage.sandbox.platform.hmcts.net/"

