{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
type: Opaque
stringData:
  AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.clientSecret }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.clientSecret }}
  AUTH_GITLAB_CLIENT_SECRET: {{ .Values.auth.gitlab.clientSecret }}
  AUTH_OKTA_CLIENT_SECRET: {{ .Values.auth.okta.clientSecret }}
  AUTH_OAUTH2_CLIENT_SECRET: {{ .Values.auth.oauth2.clientSecret }}
  SENTRY_TOKEN: {{ .Values.auth.sentryToken }}
  ROLLBAR_ACCOUNT_TOKEN: {{ .Values.auth.rollbarAccountToken }}
  POSTGRES_PASSWORD: {{ .Values.backend.db.password }}
  AUTH_MICROSOFT_CLIENT_ID: {{ .Values.auth.microsoft.client_id }}
  AUTH_MICROSOFT_CLIENT_SECRET: {{ .Values.auth.microsoft.client_secret }}
  AUTH_MICROSOFT_TENANT_ID: {{ .Values.auth.microsoft.tenant_id }}
  GITHUB_ACCESS_TOKEN: {{ .Values.scaffolder.githubToken }}
  JENKINS_BASIC_AUTH_HEADER: {{ .Values.jenkins.authHeader }}
{{- end }}
