{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
type: Opaque
stringData:
  AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.clientSecret }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.clientSecret }}
  AUTH_GITLAB_CLIENT_SECRET: {{ .Values.auth.gitlab.clientSecret }}
  AUTH_OKTA_CLIENT_SECRET: {{ .Values.auth.okta.clientSecret }}
  AUTH_OAUTH2_CLIENT_SECRET: {{ .Values.auth.oauth2.clientSecret }}
  SENTRY_TOKEN: {{ .Values.auth.sentryToken }}
  ROLLBAR_ACCOUNT_TOKEN: {{ .Values.auth.rollbarAccountToken }}
{{- end }}
