{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
type: Opaque
stringData:
  AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.clientSecret }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.clientSecret }}
  AUTH_GITLAB_CLIENT_SECRET: {{ .Values.auth.gitlab.clientSecret }}
  AUTH_OKTA_CLIENT_SECRET: {{ .Values.auth.okta.clientSecret }}
  AUTH_OAUTH2_CLIENT_SECRET: {{ .Values.auth.oauth2.clientSecret }}
  AUTH_AUTH0_CLIENT_SECRET: {{ .Values.auth.auth0.clientSecret }}
  AUTH_MICROSOFT_CLIENT_SECRET: {{ .Values.auth.microsoft.clientSecret }}
  SENTRY_TOKEN: {{ .Values.auth.sentryToken }}
  ROLLBAR_ACCOUNT_TOKEN: {{ .Values.auth.rollbarAccountToken }}
  CIRCLECI_AUTH_TOKEN: {{ .Values.auth.circleciAuthToken }}
  GITHUB_ACCESS_TOKEN: {{ .Values.auth.githubAccessToken }}
  GITLAB_ACCESS_TOKEN: {{ .Values.auth.gitlabAccessToken }}
{{- end }}
{{- if .Values.lighthouse.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-pg
type: Opaque
stringData:
  # Need to duplicate some values because lighthouse expects different environment variable
  # names than Backstage does.
  PGPASSWORD: {{ .Values.lighthouse.database.connection.password }}
  APP_CONFIG_backend_database_connection_password: {{ .Values.appConfig.backend.database.connection.password | quote | quote }}
{{- end }}
