{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
type: Opaque
stringData:
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.clientSecret }}
  AUTH_MICROSOFT_CLIENT_SECRET: {{ .Values.auth.microsoft.client_secret }}
  POSTGRES_PASSWORD: {{ .Values.backend.db.password }}
  GITHUB_TOKEN: {{ .Values.scaffolder.githubToken }}
  JENKINS_BASIC_AUTH_HEADER: {{ .Values.jenkins.authHeader }}
{{- end }}
