{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-frontend

spec:
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}

  selector:
    app: backstage
    component: frontend

  type: ClusterIP
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-backend

spec:
  ports:
    - port: 80
      targetPort: {{ .Values.backend.containerPort }}

  selector:
    app: backstage
    component: backend

  type: ClusterIP
{{- end }}

{{- if .Values.lighthouse.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-lighthouse

spec:
  ports:
    - port: 80
      targetPort: {{ .Values.lighthouse.containerPort }}

  selector:
    app: backstage
    component: lighthouse-audit-service

  type: ClusterIP
{{- end }}
