{{ if .Values.broker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.broker.serviceAccount.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.broker.deployment.name }}
  labels:
    app: roadie-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadie-broker
  template:
    metadata:
      labels:
        app: roadie-broker
    spec:
      serviceAccountName: {{ .Values.broker.serviceAccount.name }}
      {{ if .Values.broker.imagePullSecret -}}
      imagePullSecrets:
        - name: {{ .Values.broker.imagePullSecret }}
      {{ end -}}
      containers:
        - name: roadie-broker
          image: {{ .Values.broker.image }}
          imagePullPolicy: Always
          env:
            - name: BROKER_TOKEN
              value: {{ .Values.broker.token }}
            - name: BROKER_SERVER_URL
              value: https://{{ .Values.broker.tenantName }}.broker.roadie.so
            - name: CA_CERT
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - name: LOG_LEVEL
              value: {{ .Values.broker.logLevel }}
            - name: LOG_ENABLE_BODY
              value: "{{ .Values.broker.logBody }}"
            {{- if .Values.broker.env }}
            {{- toYaml .Values.broker.env | nindent 12 }}
            {{- end }}
            {{- if .Values.broker.envFrom }}
          envFrom:
            {{- toYaml .Values.broker.envFrom | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8000
          {{- if .Values.broker.securityContext }}
          securityContext:
{{ toYaml .Values.broker.securityContext | indent 12 }}
          {{- end}}
{{ end }}
