{{ if .Values.broker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.broker.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: roadie-broker-pod-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.broker.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.broker.deployment.name }}
  labels:
    app: roadie-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadie-broker
  template:
    metadata:
      labels:
        app: roadie-broker
    spec:
      serviceAccountName: {{ .Values.broker.serviceAccount.name }}
      containers:
        - name: roadie-broker
          image: {{ .Values.broker.image }}
          imagePullPolicy: Always
          env:
            - name: BROKER_TOKEN
              value: {{ .Values.broker.token }}
            - name: BROKER_SERVER_URL
              value: https://{{ .Values.broker.tenantName }}.broker.roadie.so
            - name: CA_CERT
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          ports:
            - containerPort: 8000
{{ end }}