---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name | default (printf "%s-cluster-role" .Release.Name) }}
rules:
  {{- toYaml .Values.clusterRole.rules.set1 | nindent 2 }}
  {{- toYaml .Values.clusterRole.rules.set2 | nindent 2 }}
  {{- toYaml .Values.clusterRole.rules.set3 | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name | default (printf "%s-role-binding" .Release.Name) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole.name | default (printf "%s-cluster-role" .Release.Name) }}
subjects:
  {{ if and (eq .Values.serviceAccount.enabled true)  (eq .Values.broker.enabled false)}}
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.serviceAccount.namespace }}
  {{ else }}
  - kind: User
    name: {{ .Values.user.name }}
  {{ end }}
